### ISSUE TITLE
stylelint error after a clean global install

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/lints#8]
```sh
npm install lints -g
lints
```

```
{ Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
    at exports.default (/usr/local/lib/node_modules/lints/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at exports.default (/usr/local/lib/node_modules/lints/node_modules/stylelint/dist/utils/getModulePath.js:15:36)
    at loadExtendedConfig (/usr/local/lib/node_modules/lints/node_modules/stylelint/dist/augmentConfig.js:186:45)
    at /usr/local/lib/node_modules/lints/node_modules/stylelint/dist/augmentConfig.js:173:14 code: 78 }
```

**Comment by EvgenyOrekhov** [comment]
As a temporary workaround, you can install stylelint-config-standard locally:

```sh
npm install stylelint-config-standard --save-dev
```

But you would have to do this for every project you would want to lint with globally-installed lints.

**Comment by EvgenyOrekhov** [comment]
There is an open issue about it in the stylelint repo: https://github.com/stylelint/stylelint/issues/1973
